### Post request - Create a new employee
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "RICARDO",
  "pin": "001",
  "ssn": 1,
  "age": 36,
  "salary": 3800
}

### Get request - Find All employees
GET http://localhost:8080/employees

### Get request - Find By SSN
GET http://localhost:8080/employees/ssn/12

### Get request - Find All employees where age is less than 50
GET http://localhost:8080/employees/filter/age-less-than?age=2

### Get request - Find All employee where salary is greater than x
GET http://localhost:8080/employees/filter/salary-greater-than?salary=100.0